/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.ui.home;

import com.client.common.Common;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ngao
 */
public class PanelCall extends javax.swing.JPanel implements ICallContract.IView {

    private ICallContract.IPresenter presenter;

    /**
     * Creates new form Home
     */
    public PanelCall() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tb_pathFileAudio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tb_toUser = new javax.swing.JTextField();
        tb_error = new javax.swing.JLabel();
        bt_call = new javax.swing.JButton();
        bt_off = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tb_idUser = new javax.swing.JLabel();

        jLabel1.setText("Chọn file âm thanh giả để làm cuộc gọi. các file hợp lệ có loại wav");

        tb_pathFileAudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_pathFileAudioMouseClicked(evt);
            }
        });

        jLabel2.setText("Nhập id người nhận để liên lạc");

        tb_error.setForeground(new java.awt.Color(241, 22, 22));

        bt_call.setText("Gọi");
        bt_call.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_callMouseOnClick(evt);
            }
        });

        bt_off.setText("Kết thúc gọi");

        jLabel3.setText("Xin chào: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb_idUser, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(tb_toUser, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(121, 121, 121)
                            .addComponent(bt_call, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bt_off, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addComponent(tb_error, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tb_pathFileAudio, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb_idUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_pathFileAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_toUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_call)
                    .addComponent(bt_off))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_pathFileAudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_pathFileAudioMouseClicked
        JFileChooser file = new JFileChooser();
        file.setFileFilter(new FileNameExtensionFilter("wav", "wav"));
        file.setMultiSelectionEnabled(true);
        file.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        file.setFileHidingEnabled(false);
        if (file.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            java.io.File f = file.getSelectedFile();
            tb_pathFileAudio.setText(f.getAbsolutePath());
        }
    }//GEN-LAST:event_tb_pathFileAudioMouseClicked

    private void bt_callMouseOnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_callMouseOnClick
        presenter.call();
    }//GEN-LAST:event_bt_callMouseOnClick


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_call;
    private javax.swing.JButton bt_off;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel tb_error;
    private javax.swing.JLabel tb_idUser;
    private javax.swing.JTextField tb_pathFileAudio;
    private javax.swing.JTextField tb_toUser;
    // End of variables declaration//GEN-END:variables

    @Override
    public void showMeg(String meg) {
        this.tb_error.setText(meg);
    }

    @Override
    public void init() {
        presenter = new CallPresenter();
        presenter.setView(this);
        this.tb_idUser.setText(Common.Main.connection.getUser());
    }

    @Override
    public String getUrlAudio() {
        return this.tb_pathFileAudio.getText();
    }

    @Override
    public String getToUser() {
        return tb_toUser.getText();
    }
}
